#!/bin/bash -e
if [[ ! -f "/home/spark-9a5b800f-5f56-4e5c-bf91-a2/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-9a5b800f-5f56-4e5c-bf91-a2/tmp/uv/uv_0.6.10_linux_amd64" "$@"
